import { Service, Package, Review } from "@/types";

export const SERVICES: Service[] = [
  {
    id: "1",
    title: "Bloom & Petal Decorations",
    category: "Decor",
    description:
      "Award-winning floral and event decor specialists. We transform spaces with stunning floral arrangements, lighting, and themed decorations for all occasions.",
    location: "Los Angeles",
    price_min: 800,
    price_max: 5000,
    price_unit: "per event",
    rating: 4.9,
    review_count: 124,
    image_url: "/images/featured-services/featured-services-1.jpg",
    vendor_name: "Sarah Johnson",
    vendor_email: "sarah@bloomandpetal.com",
    vendor_phone: "+1 (555) 234-5678",
    tags: ["Birthday", "Wedding", "Proposal", "Baby Shower"],
    gallery: [
      "/images/featured-services/featured-gallery/featured-gallery-1.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-2.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-3.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-4.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-5.jpg",
    ],
    features: [
      "Custom floral arrangements",
      "Lighting design",
      "Table centerpieces",
      "Backdrop setup",
      "Same-day setup",
    ],
    created_at: "2024-01-15",
  },
  {
    id: "2",
    title: "Savory Bites Catering",
    category: "Catering",
    description:
      "Premium catering service offering diverse international cuisines. From elegant plated dinners to lavish buffets.",
    location: "Chicago",
    price_min: 45,
    price_max: 150,
    price_unit: "per person",
    rating: 4.7,
    review_count: 89,
    image_url: "/images/featured-services/featured-services-2.jpg",
    vendor_name: "Marco Rossi",
    vendor_email: "marco@savorybites.com",
    vendor_phone: "+1 (555) 345-6789",
    tags: ["Corporate", "Wedding", "Birthday", "Graduation"],
    gallery: [
      "/images/featured-services/featured-gallery/featured-gallery-6.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-7.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-8.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-9.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-10.jpg",
    ],
    features: [
      "International cuisine",
      "Custom menus",
      "Professional staff",
      "Bar service",
      "Dietary accommodations",
    ],
    created_at: "2024-02-01",
  },
  {
    id: "3",
    title: "Royal Feast Banquet Catering",
    category: "Catering",
    description:
      "Luxury banquet-style catering with a focus on South Asian, Mediterranean, and fusion cuisines.",
    location: "Houston",
    price_min: 60,
    price_max: 200,
    price_unit: "per person",
    rating: 4.8,
    review_count: 67,
    image_url: "/images/featured-services/featured-services-3.jpg",
    vendor_name: "Aisha Rahman",
    vendor_email: "aisha@royalfeast.com",
    vendor_phone: "+1 (555) 456-7890",
    tags: ["Wedding", "Corporate", "Eid", "Diwali"],
    gallery: [
      "/images/featured-services/featured-gallery/featured-gallery-11.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-12.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-13.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-14.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-15.jpg",
    ],
    features: [
      "South Asian cuisine",
      "Live cooking stations",
      "Dessert buffet",
      "Halal options",
      "Premium tableware",
    ],
    created_at: "2024-02-10",
  },
  {
    id: "4",
    title: "Electric Vibes DJ & Entertainment",
    category: "Entertainment",
    description:
      "Top-rated DJ and entertainment service bringing the energy to every event. State-of-the-art sound and lighting equipment.",
    location: "Miami",
    price_min: 500,
    price_max: 3000,
    price_unit: "per event",
    rating: 4.6,
    review_count: 203,
    image_url: "/images/featured-services/featured-services-4.jpg",
    vendor_name: "DJ Marcus",
    vendor_email: "marcus@electricvibes.com",
    vendor_phone: "+1 (555) 567-8901",
    tags: ["Birthday", "Wedding", "Corporate", "Festival"],
    gallery: [
      "/images/featured-services/featured-gallery/featured-gallery-16.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-17.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-18.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-19.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-20.jpg",
    ],
    features: [
      "Professional DJ equipment",
      "LED light show",
      "Live mixing",
      "MC services",
      "Custom playlist",
    ],
    created_at: "2024-01-20",
  },
  {
    id: "5",
    title: "Sunset Terrace Gardens",
    category: "Venue",
    description:
      "A breathtaking outdoor venue nestled in lush gardens with panoramic sunset views. Ideal for weddings, corporate events, and private parties.",
    location: "San Francisco",
    price_min: 2000,
    price_max: 8000,
    price_unit: "per event",
    rating: 4.9,
    review_count: 156,
    image_url: "/images/featured-services/featured-services-5.jpg",
    vendor_name: "Elena Vasquez",
    vendor_email: "elena@sunsetterrace.com",
    vendor_phone: "+1 (555) 678-9012",
    tags: ["Wedding", "Corporate", "Birthday", "Proposal"],
    gallery: [
      "/images/featured-services/featured-gallery/featured-gallery-21.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-22.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-23.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-24.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-25.jpg",
    ],
    features: [
      "Capacity up to 300 guests",
      "Outdoor terrace",
      "Bridal suite",
      "Parking available",
      "In-house catering kitchen",
    ],
    created_at: "2024-01-05",
  },
  {
    id: "6",
    title: "The Grand Palace Ballroom",
    category: "Venue",
    description:
      "An exquisite ballroom venue with crystal chandeliers, marble floors, and capacity for up to 500 guests. Perfect for grand celebrations.",
    location: "New York",
    price_min: 3000,
    price_max: 12000,
    price_unit: "per event",
    rating: 4.8,
    review_count: 198,
    image_url: "/images/featured-services/featured-services-6.jpg",
    vendor_name: "Grand Palace Events",
    vendor_email: "events@grandpalace.com",
    vendor_phone: "+1 (555) 789-0123",
    tags: ["Wedding", "Gala", "Corporate", "Anniversary"],
    gallery: [
      "/images/featured-services/featured-gallery/featured-gallery-26.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-27.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-28.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-29.jpg",
      "/images/featured-services/featured-gallery/featured-gallery-21.jpg",
    ],
    features: [
      "Capacity up to 500 guests",
      "Crystal chandeliers",
      "Marble flooring",
      "Multiple event rooms",
      "Valet parking",
      "Audio/visual equipment",
    ],
    created_at: "2024-01-01",
  },
];

export const PACKAGES: Package[] = [
  {
    id: "p1",
    service_id: "6",
    title: "Grand Wedding Essentials",
    description: "Everything you need for a perfect wedding reception",
    price: 5500,
    inclusions: [
      "8 hours venue rental",
      "Crystal chandelier lighting",
      "Bridal suite access",
      "Basic floral centerpieces",
      "Dedicated event coordinator",
      "Setup & cleanup",
    ],
    max_guests: 200,
    duration_hours: 8,
    is_popular: true,
  },
  {
    id: "p2",
    service_id: "6",
    title: "Corporate Gala Package",
    description: "Professional setup for corporate events and galas",
    price: 8000,
    inclusions: [
      "10 hours venue rental",
      "AV equipment included",
      "Stage and podium setup",
      "VIP lounge area",
      "Corporate branding options",
      "Catering coordination",
    ],
    max_guests: 400,
    duration_hours: 10,
  },
  {
    id: "p3",
    service_id: "1",
    title: "Romance in Bloom",
    description:
      "Intimate floral setup perfect for proposals and anniversaries",
    price: 1800,
    inclusions: [
      "Custom floral arch",
      "Rose petal pathway",
      "10 table centerpieces",
      "Ambient candle lighting",
      "Personalized signage",
    ],
    max_guests: 50,
    duration_hours: 6,
    is_popular: true,
  },
  {
    id: "p4",
    service_id: "1",
    title: "Grand Celebration Decor",
    description: "Full venue transformation for large-scale events",
    price: 3500,
    inclusions: [
      "Full venue floral decor",
      "LED backdrop wall",
      "Ceiling draping",
      "20+ table centerpieces",
      "Photo booth corner setup",
      "Entry arch installation",
    ],
    max_guests: 300,
    duration_hours: 12,
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    service_id: "6",
    reviewer_name: "Shwetha",
    reviewer_avatar: "/images/team/team-1.jpg",
    rating: 5,
    comment:
      "We worked with the EventStan Team for our event, and I have to say — they did an absolutely incredible job. The entire event was handled with professionalism and attention to detail. A special appreciation to Suraj, who went above and beyond from start to finish. His coordination, patience, and problem-solving made a huge difference throughout the planning and execution. Every requirement was taken care of smoothly, and the team ensured the day ran flawlessly.",
    event_type: "Conference",
    location: "Dubai",
    created_at: "2024-03-15",
  },
  {
    id: "r2",
    service_id: "2",
    reviewer_name: "Mitali",
    reviewer_avatar: "/images/team/team-2.jpg",
    rating: 5,
    comment:
      "Cannot thank Mehak and her team enough for organizing our first event! Since we had never done this before, we were really nervous, but we were amazed by how supportive, helpful and professional Eventstan is. From finding us the best vendors, ensuring every little detail is perfect and just how beautifully they executed our engagement ceremony…. we are so grateful and cannot wait to host our next event with you guys ❤️",
    event_type: "Corporate Gala",
    location: "Chicago",
    created_at: "2024-02-28",
  },
  {
    id: "r3",
    service_id: "4",
    reviewer_name: "Saira Zia",
    reviewer_avatar: "/images/team/team-3.jpg",
    rating: 5,
    comment:
      "I had such an amazing experience with Event Stan! Especially with MEHAK From start to finish, her team was so professional, punctual, and incredibly easy to work with. She truly understood my vision and brought it to life perfectly — all with such calmness and grace. Her attention to detail and the way she handled everything so smoothly made the whole event stress-free and absolutely beautiful. I’m so glad I chose Event stan and would highly recommend Event Stan to anyone looking for a reliable and creative event team!",
    event_type: "Dinner Party",
    location: "Abudhbai",
    created_at: "2024-03-01",
  },
  {
    id: "r4",
    service_id: "1",
    reviewer_name: "Vaibhav Makkar - Careem",
    reviewer_avatar: "/images/team/team-4.jpg",
    rating: 5,
    comment:
      "The EventStan team did a phenomenal job organizing our recent event. Everything from planning and coordination to on-ground execution- was seamless. The setup looked beautiful, the atmosphere was warm and engaging, and every detail was handled with precision and care. Their professionalism and creativity truly stood out. The team was proactive, quick to respond, and incredibly accommodating, ensuring that everything ran smoothly without us having to worry about a thing. A special thanks to Mehak for personally managing the finer details and coordinating with all vendors to perfection. Your commitment and ownership made all the difference. Highly recommend EventStan to anyone looking for a dependable, creative, and hands-on events partner who delivers excellence end-to-end.",
    event_type: "Team Outing",
    location: "Dubai",
    created_at: "2024-02-14",
  },
  {
    id: "r5",
    service_id: "3",
    reviewer_name: "Acube Reality",
    reviewer_avatar: "/images/team/team-5.jpg",
    rating: 4,
    comment:
      "Had a wonderful experience with the Event Team! Special thanks to Mr. Suraj, Ms. Mehak, and Ms. Aashi for their professionalism, coordination, and positive attitude throughout the event. Everything was well managed and executed smoothly. Their dedication truly made a difference. Highly recommended!",
    event_type: "Ground Breaking",
    location: "Dubai",
    created_at: "2024-01-20",
  },
  {
    id: "r6",
    service_id: "5",
    reviewer_name: "Pooja Solanki",
    reviewer_avatar: "/images/team/team-6.jpg",
    rating: 4,
    comment:
      "Hi my name is Pooja and Eventstan planned and managed our wedding for 2 days in Dubai. We are beyond grateful to have choosing them. From start to finish, they truly took care of everything, allowing us and our families to enjoy each moment stress-free. They flawlessly managed all our events — mehendi, haldi, sangeet, and the wedding — with incredible attention to detail. From stunning décor management and smooth logistics to excellent food management and warm guest hospitality, every aspect was perfectly executed. What truly stood out was their professionalism, responsiveness, and ability to handle last-minute requests from us to Mahek and Suraj, and they calmly managed all so well. Our guests couldn’t stop complimenting how well-organized and beautiful each event was. Thank you for turning our vision into reality and making our wedding experience so memorable and smooth. We couldn’t have asked for a better team and highly recommend them to anyone planning a wedding in Dubai! ",
    event_type: "Wedding",
    location: "Dubai",
    created_at: "2024-03-10",
  },
  {
    id: "r7",
    service_id: "5",
    reviewer_name: "Venessa D'souza",
    reviewer_avatar: "/images/team/team-6.jpg",
    rating: 4,
    comment:
      "It was my first time working with Mehak and the team, and the experience exceeded our expectations. From start to finish, they were professional, organized, and highly responsive. Every detail was handled smoothly, and their coordination ensured everything ran seamlessly. They delivered a very successful event for us, and we truly appreciate their dedication and commitment to excellence. I would highly recommend them and look forward to working together again. ",
    event_type: "Marketing - Funcity",
    location: "Dubai",    
    created_at: "2024-03-10",
  },
];

export const CATEGORY_FILTERS: Record<string, string[]> = {
  Venue: [
    "Wedding",
    "Corporate",
    "Birthday",
    "Anniversary",
    "Graduation",
    "Party",
  ],
  Decor: [
    "Birthday",
    "Proposal",
    "Baby Shower",
    "Wedding",
    "Corporate",
    "Festival",
  ],
  Catering: [
    "Wedding Banquet",
    "Corporate Lunch",
    "Birthday Party",
    "Cocktail Party",
    "Buffet",
    "Live Station",
  ],
  Entertainment: [
    "DJ Night",
    "Live Band",
    "Comedy Show",
    "Magic Show",
    "Photo Booth",
    "Kids Entertainment",
  ],
};
