import { Booking, Service, Package, VendorStats } from './types';

export const mockStats: VendorStats = {
  totalBookings: 47,
  pendingBookings: 6,
  confirmedBookings: 38,
  totalRevenue: 142500,
  pendingRevenue: 18000,
  averageRating: 4.8,
  totalServices: 5,
};

export const mockBookings: Booking[] = [
  {
    id: 'BK-001',
    customerName: 'Fatima Al-Rashid',
    customerEmail: 'fatima@example.com',
    customerPhone: '+971 50 123 4567',
    serviceName: 'Grand Ballroom Package',
    eventType: 'Wedding',
    eventDate: '2026-05-15',
    eventVenue: 'Al Noor Island, Sharjah',
    guests: 200,
    amount: 12000,
    paidAmount: 6000,
    status: 'Pending',
    createdAt: '2026-04-20',
    message: 'We need extra floral arrangements for the entrance. Also can you arrange a special backdrop for photos?',
  },
  {
    id: 'BK-002',
    customerName: 'Ahmed Hassan',
    customerEmail: 'ahmed@example.com',
    customerPhone: '+971 55 987 6543',
    serviceName: 'Corporate Catering',
    eventType: 'Corporate Event',
    eventDate: '2026-05-10',
    eventVenue: 'Dubai World Trade Centre',
    guests: 150,
    amount: 8500,
    paidAmount: 4250,
    status: 'Accepted',
    createdAt: '2026-04-18',
  },
  {
    id: 'BK-003',
    customerName: 'Sara Mohammed',
    customerEmail: 'sara@example.com',
    customerPhone: '+971 52 456 7890',
    serviceName: 'Luxury Decoration',
    eventType: 'Birthday Party',
    eventDate: '2026-05-22',
    eventVenue: 'The Palm Jumeirah Villa',
    guests: 80,
    amount: 3500,
    paidAmount: 3500,
    status: 'Confirmed',
    createdAt: '2026-04-15',
    message: 'Pink and gold theme. Surprise party so please coordinate with Ahmed only.',
  },
  {
    id: 'BK-004',
    customerName: 'Omar Abdullah',
    customerEmail: 'omar@example.com',
    customerPhone: '+971 56 321 0987',
    serviceName: 'Premium Venue',
    eventType: 'Wedding',
    eventDate: '2026-06-05',
    eventVenue: 'Ritz Carlton, Abu Dhabi',
    guests: 300,
    amount: 18000,
    paidAmount: 9000,
    status: 'Pending',
    createdAt: '2026-04-22',
    message: 'Looking for valet parking arrangements too. Let me know if that can be arranged.',
  },
  {
    id: 'BK-005',
    customerName: 'Layla Khalid',
    customerEmail: 'layla@example.com',
    customerPhone: '+971 54 654 3210',
    serviceName: 'DJ Entertainment',
    eventType: 'Anniversary',
    eventDate: '2026-05-30',
    eventVenue: 'Burj Al Arab Terrace',
    guests: 60,
    amount: 2500,
    paidAmount: 2500,
    status: 'Payment Pending (Balance)',
    createdAt: '2026-04-10',
  },
  {
    id: 'BK-006',
    customerName: 'Khalid Ibrahim',
    customerEmail: 'khalid@example.com',
    customerPhone: '+971 50 789 0123',
    serviceName: 'Outdoor Garden Venue',
    eventType: 'Baby Shower',
    eventDate: '2026-05-08',
    eventVenue: 'Emirates Hills',
    guests: 40,
    amount: 4200,
    paidAmount: 0,
    status: 'Rejected (Vendor)',
    createdAt: '2026-04-08',
  },
  {
    id: 'BK-007',
    customerName: 'Nora Al-Sayed',
    customerEmail: 'nora@example.com',
    customerPhone: '+971 55 234 5678',
    serviceName: 'Grand Ballroom Package',
    eventType: 'Graduation',
    eventDate: '2026-07-12',
    eventVenue: 'Atlantis The Palm',
    guests: 120,
    amount: 7500,
    paidAmount: 3750,
    status: 'Accepted',
    createdAt: '2026-04-19',
  },
  {
    id: 'BK-008',
    customerName: 'Zayed Al-Mansoori',
    customerEmail: 'zayed@example.com',
    customerPhone: '+971 52 111 2233',
    serviceName: 'Premium Buffet Catering',
    eventType: 'Corporate Event',
    eventDate: '2026-06-20',
    eventVenue: 'DIFC Conference Centre',
    guests: 250,
    amount: 11250,
    paidAmount: 5625,
    status: 'Confirmed',
    createdAt: '2026-04-25',
    message: 'Halal only. No pork products. VIP section needs separate plating.',
  },
];

export const mockServices: Service[] = [
  {
    id: 'SV-001',
    name: 'Grand Ballroom',
    category: 'Venue',
    description: 'Exquisite ballroom with crystal chandeliers and marble floors. Capacity up to 500 guests.',
    priceMin: 5000,
    priceMax: 15000,
    priceUnit: 'per event',
    images: ['https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80'],
    isActive: true,
    rating: 4.9,
    totalBookings: 23,
  },
  {
    id: 'SV-002',
    name: 'Outdoor Garden Venue',
    category: 'Venue',
    description: 'Beautiful garden setting with panoramic views. Perfect for outdoor weddings and events.',
    priceMin: 3000,
    priceMax: 8000,
    priceUnit: 'per event',
    images: ['https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600&q=80'],
    isActive: true,
    rating: 4.7,
    totalBookings: 15,
  },
  {
    id: 'SV-003',
    name: 'Luxury Floral Decoration',
    category: 'Decoration',
    description: 'Premium floral arrangements and thematic decorations for all event types.',
    priceMin: 1500,
    priceMax: 6000,
    priceUnit: 'per event',
    images: ['https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&q=80'],
    isActive: true,
    rating: 4.8,
    totalBookings: 31,
  },
  {
    id: 'SV-004',
    name: 'Premium Buffet Catering',
    category: 'Catering',
    description: 'International cuisine buffets featuring Middle Eastern, Asian, and Western dishes.',
    priceMin: 45,
    priceMax: 150,
    priceUnit: 'per person',
    images: ['https://images.unsplash.com/photo-1555244162-803834f70033?w=600&q=80'],
    isActive: false,
    rating: 4.6,
    totalBookings: 18,
  },
  {
    id: 'SV-005',
    name: 'DJ & Sound System',
    category: 'Entertainment',
    description: 'Professional DJ services with state-of-the-art sound and lighting equipment.',
    priceMin: 800,
    priceMax: 3500,
    priceUnit: 'per event',
    images: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80'],
    isActive: true,
    rating: 4.9,
    totalBookings: 12,
  },
];

export const mockPackages: Package[] = [
  {
    id: 'PKG-001',
    name: 'Royal Wedding Package',
    description: 'All-inclusive wedding package with venue, decoration, catering, and entertainment.',
    price: 25000,
    services: ['SV-001', 'SV-003', 'SV-004', 'SV-005'],
    discount: 15,
    isActive: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'PKG-002',
    name: 'Corporate Event Bundle',
    description: 'Professional setup for corporate events, conferences, and product launches.',
    price: 12000,
    services: ['SV-001', 'SV-004'],
    discount: 10,
    isActive: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'PKG-003',
    name: 'Garden Celebration',
    description: 'Outdoor celebration package with garden venue and decorations.',
    price: 8500,
    services: ['SV-002', 'SV-003'],
    discount: 8,
    isActive: false,
    createdAt: '2026-03-05',
  },
];

export const revenueData = [
  { month: 'Nov', revenue: 18000 },
  { month: 'Dec', revenue: 24000 },
  { month: 'Jan', revenue: 19500 },
  { month: 'Feb', revenue: 28000 },
  { month: 'Mar', revenue: 22000 },
  { month: 'Apr', revenue: 31000 },
];

export const bookingsByMonth = [
  { month: 'Nov', bookings: 5 },
  { month: 'Dec', bookings: 8 },
  { month: 'Jan', bookings: 6 },
  { month: 'Feb', bookings: 10 },
  { month: 'Mar', bookings: 9 },
  { month: 'Apr', bookings: 9 },
];
