import { Promotion } from "@/types";

export const PROMOTIONS: Promotion[] = [
  {
    id: "promo-1",
    title: "Neural Entertainment Couple Entry",
    vendor_name: "Neural Entertainment",
    vendor_handle: "mrsrivastava",
    category: "Entertainment",
    image_url: "/images/previous-works/previous-work-7.jpg",
    description: "Couple Entry on great price. Enjoy an exclusive entertainment experience with premium stage shows, live performances, and full production value.",
    short_desc: "Couple Entry on great price",
    price: 800,
    price_unit: "per person",
    max_guests: 400,
    duration_hours: 6,
    inclusions: ["Snacks Free", "Unlimited Drinks", "VIP Seating", "Professional Sound"],
    badge: "Entertainment",
    is_featured: true,
    expires_at: "2024-12-31",
    original_price: 1100,
    service_id: "4",
  },
  {
    id: "promo-2",
    title: "Neural Premium Birthday Event",
    vendor_name: "Neural Entertainment",
    vendor_handle: "mrsrivastava",
    category: "Venue",
    image_url: "/images/promotions/promotions-1.jpg",
    description: "This is one of great promotions for Birthday Parties. A complete birthday celebration package in a stunning venue with all essentials included.",
    short_desc: "This is one of great promotions for Birthday Parties.",
    price: 45000,
    price_unit: "per day",
    max_guests: 50,
    duration_hours: 6,
    inclusions: ["Free Water", "Free Parking", "Free Sweets", "Birthday Décor", "DJ System"],
    badge: "Venue",
    expires_at: "2024-11-30",
    original_price: 58000,
    service_id: "5",
  },
  {
    id: "promo-3",
    title: "Large Frame Marquee (10x20m)",
    vendor_name: "Canopy Event Structures",
    vendor_handle: "canopyevents",
    category: "Rentals",
    image_url: "/images/previous-works/previous-work-4.jpg",
    description: "Our flagship marquee for large weddings, corporate galas, and festivals. Seats 150–200 guests in style. Waterproof, fully lined with sidewalls included.",
    short_desc: "Our flagship marquee for large weddings, corporate galas, and festivals. Seats 150–200 guests in style...",
    price: 1200,
    price_unit: "per day",
    max_guests: 200,
    duration_hours: 24,
    inclusions: ["10×20m frame marquee", "Waterproof lining", "Sidewalls included", "Delivery included", "Setup crew"],
    badge: "Rentals",
    expires_at: "2024-12-15",
    original_price: 1600,
    service_id: "5",
  },
  {
    id: "promo-4",
    title: "Grand Ballroom Wedding Special",
    vendor_name: "Grand Palace Events",
    vendor_handle: "grandpalace",
    category: "Venue",
    image_url: "/images/promotions/promotions-1.jpg",
    description: "An exclusive wedding package inside our crystal chandelier ballroom. Accommodates up to 500 guests with marble flooring and full AV setup.",
    short_desc: "Crystal chandeliers, marble floors, capacity up to 500 guests.",
    price: 8500,
    price_unit: "per event",
    max_guests: 500,
    duration_hours: 10,
    inclusions: ["Bridal suite access", "Crystal chandelier lighting", "Valet parking", "AV equipment", "Event coordinator"],
    badge: "Venue",
    is_featured: true,
    expires_at: "2024-12-31",
    original_price: 12000,
    service_id: "6",
  },
  {
    id: "promo-5",
    title: "Bloom & Petal Wedding Decor Bundle",
    vendor_name: "Bloom & Petal Decorations",
    vendor_handle: "bloomandpetal",
    category: "Decor",
    image_url: "/images/previous-works/previous-work-4.jpg",
    description: "Full venue transformation — floral arches, table centerpieces, ceiling draping, LED backdrop, and a personalized photo booth corner.",
    short_desc: "Full venue floral transformation for your dream wedding.",
    price: 2800,
    price_unit: "per event",
    max_guests: 300,
    duration_hours: 8,
    inclusions: ["Floral arch & altar", "20+ table centerpieces", "Ceiling draping", "LED backdrop", "Photo booth corner"],
    badge: "Decor",
    expires_at: "2024-11-15",
    original_price: 3800,
    service_id: "1",
  },
  {
    id: "promo-6",
    title: "Corporate Gala Catering Package",
    vendor_name: "Savory Bites Catering",
    vendor_handle: "savorybites",
    category: "Catering",
    image_url: "/images/previous-works/previous-work-4.jpg",
    description: "Premium catering service for corporate events. Multi-cuisine buffet with live cooking stations, dessert spreads, and professional waitstaff.",
    short_desc: "Multi-cuisine buffet with live stations for corporate events.",
    price: 85,
    price_unit: "per person",
    max_guests: 300,
    duration_hours: 5,
    inclusions: ["Multi-cuisine buffet", "Live cooking stations", "Dessert spread", "Professional waitstaff", "Table setup"],
    badge: "Catering",
    expires_at: "2024-12-31",
    original_price: 120,
    service_id: "2",
  },
  {
    id: "promo-7",
    title: "DJ Night — Festival Package",
    vendor_name: "Electric Vibes DJ",
    vendor_handle: "electricvibes",
    category: "Entertainment",
    image_url: "/images/previous-works/previous-work-4.jpg",
    description: "Full DJ festival setup with LED light show, professional sound system, MC hosting, and a custom playlist tailored to your crowd.",
    short_desc: "Full DJ setup with LED show, MC hosting & custom playlist.",
    price: 2200,
    price_unit: "per event",
    max_guests: 600,
    duration_hours: 8,
    inclusions: ["Professional DJ system", "LED light show", "MC services", "Custom playlist", "Setup & breakdown"],
    badge: "Entertainment",
    expires_at: "2024-12-20",
    original_price: 3000,
    service_id: "4",
  },
  {
    id: "promo-8",
    title: "Sunset Garden — Intimate Proposal Setup",
    vendor_name: "Sunset Terrace Gardens",
    vendor_handle: "sunsetterrace",
    category: "Venue",
    image_url: "/images/promotions/promotions-1.jpg",
    description: "Romantic outdoor proposal setup in our lush garden terrace with floral pathway, candles, private dining, and photography coordination.",
    short_desc: "Romantic proposal setup with florals, candles & private dining.",
    price: 1400,
    price_unit: "per event",
    max_guests: 10,
    duration_hours: 4,
    inclusions: ["Rose petal pathway", "Candle arrangement", "Private dining setup", "Floral arch", "Photography guidance"],
    badge: "Venue",
    is_featured: true,
    expires_at: "2024-12-31",
    original_price: 2000,
    service_id: "5",
  },
  {
    id: "promo-9",
    title: "Royal Feast Baby Shower Bundle",
    vendor_name: "Royal Feast Banquet Catering",
    vendor_handle: "royalfeast",
    category: "Catering",
    image_url: "/images/promotions/promotions-1.jpg",
    description: "A beautifully curated baby shower catering package with pastel-themed dessert bar, brunch platters, mocktails, and personalized cake.",
    short_desc: "Pastel dessert bar, brunch platters & personalized baby cake.",
    price: 55,
    price_unit: "per person",
    max_guests: 80,
    duration_hours: 4,
    inclusions: ["Brunch platters", "Dessert bar", "Baby cake", "Mocktails", "Themed tableware"],
    badge: "Catering",
    expires_at: "2024-11-30",
    original_price: 75,
    service_id: "3",
  },
];
